services:

  react-pizza-fe:
    build:
      context: https://github.com/FreemaHG/react-pizza-fe.git
    ports:
      - 80:80
    depends_on:
      - fastapi-pizza-be

  fastapi-pizza-be:
    build:
      context: .
    container_name: fastapi-pizza-be
    restart: on-failure
    expose:
      - 8000
    ports:
      - 8000:8000
    command: [ "/docker/api.sh" ]
    depends_on:
      fastapi-pizza-postgres:
        condition: service_healthy

  fastapi-pizza-postgres:
    image: postgres:latest
    env_file:
      - .env.prod
    container_name: fastapi-pizza-postgres
    restart: always
    command: -p 5432
    ports:
      - 5432:5432
    volumes:
      - fastapi-pizza-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  fastapi-pizza-postgres: