"""Create category, pizza and cart

Revision ID: da9b829c9567
Revises: 
Create Date: 2024-10-06 18:11:32.078907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9b829c9567'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('dough_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Enum('slim', 'traditional', name='doughtype'), nullable=False),
    sa.Column('price_rise', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dough_type_id'), 'dough_type', ['id'], unique=False)
    op.create_table('pizza_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Enum('small', 'average', 'big', name='sizetype'), nullable=False),
    sa.Column('price_rise', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pizza_size_id'), 'pizza_size', ['id'], unique=False)
    op.create_table('pizza',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pizza_id'), 'pizza', ['id'], unique=False)
    op.create_table('cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['size_id'], ['pizza_size.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type_id'], ['dough_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('ix_pizza_id'), table_name='pizza')
    op.drop_table('pizza')
    op.drop_index(op.f('ix_pizza_size_id'), table_name='pizza_size')
    op.drop_table('pizza_size')
    op.drop_index(op.f('ix_dough_type_id'), table_name='dough_type')
    op.drop_table('dough_type')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
